basePath: /
definitions:
  models.Product:
    properties:
      categoria:
        type: string
      created_at:
        type: string
      descripcion:
        type: string
      id:
        type: integer
      nombre:
        type: string
      precio:
        type: number
      proveedor:
        type: string
      stocks:
        items:
          $ref: '#/definitions/models.Stock'
        type: array
      updated_at:
        type: string
    type: object
  models.Stock:
    properties:
      cantidad:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      product_id:
        type: integer
      sucursal:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Sosa, Mariana Nazarena
  description: Esta API permite gestionar productos con GORM y Gin.
  title: Sistema Gestor de Productos API
  version: "1.0"
paths:
  /apiReader:
    get:
      consumes:
      - application/json
      parameters:
      - description: URL de la API
        in: query
        name: baseURL
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "400":
          description: Error al leer el archivo
          schema:
            type: string
      summary: Leer un archivo de datos de una API
      tags:
      - APIs
  /excelReader:
    post:
      consumes:
      - application/json
      parameters:
      - description: Ruta del archivo Excel
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "400":
          description: Error al leer el archivo
          schema:
            type: string
      summary: Leer un archivo Excel y guardarlo en la base de datos
      tags:
      - Excel
  /products:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "400":
          description: Error al obtener productos
          schema:
            type: string
      summary: Obtener todos los productos
      tags:
      - Productos
    post:
      consumes:
      - application/json
      parameters:
      - description: Producto a crear
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
        "500":
          description: Fallo al crear el producto
          schema:
            type: string
      summary: Crear un producto nuevo
      tags:
      - Productos
  /products/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID del producto
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Producto no encontrado
          schema:
            type: string
      summary: Eliminar un producto
      tags:
      - Productos
    get:
      consumes:
      - application/json
      parameters:
      - description: ID del producto
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "404":
          description: Producto no encontrado
          schema:
            type: string
      summary: Obtener un producto por su ID
      tags:
      - Productos
    put:
      consumes:
      - application/json
      parameters:
      - description: ID del producto
        in: path
        name: id
        required: true
        type: string
      - description: Producto a actualizar
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "404":
          description: Producto no encontrado
          schema:
            type: string
      summary: Actualizar un producto
      tags:
      - Productos
swagger: "2.0"
